server:
  servlet:
    context-path: /springapp
  port: 8090
spring:
  main:
    banner-mode: "off"
  h2:
    console:
      enabled: "true"
  datasource:
    url: jdbc:h2:file:./datasource/ratingapp
    platform: h2
